// Generated by npm run playlist:build. Complete year/duration manually before use.
export const PLAYLISTS = {
  "Late Night Drive": [
  {
    "id": "moh-moh-ke-dhaage",
    "title": "Moh Moh Ke Dhaage",
    "artist": "Papon",
    "film": "Dum Laga Ke Haisha",
    "year": null,
    "duration": null,
    "videoId": "T-8vVY-IECk"
  },
  {
    "id": "jab-tak",
    "title": "Jab Tak",
    "artist": "Armaan Malik",
    "film": "M.S. Dhoni: The Untold Story",
    "year": null,
    "duration": null,
    "videoId": "K-Ts-NFR62o"
  },
  {
    "id": "no-cap",
    "title": "No Cap",
    "artist": "KR$NA",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "Xgi7IAed5Tg"
  },
  {
    "id": "aaftab",
    "title": "Aaftab",
    "artist": "The Local Train",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "WlsWfqm7VRU"
  },
  {
    "id": "zara-zara",
    "title": "Zara Zara",
    "artist": "Bombay Jayashri",
    "film": "Rehnaa Hai Terre Dil Mein",
    "year": null,
    "duration": null,
    "videoId": "a71xD6RyOok"
  },
  {
    "id": "bheegi-si-bhaagi-si",
    "title": "Bheegi Si Bhaagi Si",
    "artist": "Mohit Chauhan",
    "film": "Raajneeti",
    "year": null,
    "duration": null,
    "videoId": "2JBWjIe9jQY"
  },
  {
    "id": "husn",
    "title": "Husn",
    "artist": "Anuv Jain",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "tzSXjwkFnVc"
  },
  {
    "id": "tauba-tauba",
    "title": "Tauba Tauba",
    "artist": "Karan Aujla",
    "film": "Bad Newz",
    "year": null,
    "duration": null,
    "videoId": "uTuchIYZdbM"
  },
  {
    "id": "akhiyaan-gulaab",
    "title": "Akhiyaan Gulaab",
    "artist": "Mitraz",
    "film": "Teri Baaton Mein Aisa Uljha Jiya",
    "year": null,
    "duration": null,
    "videoId": "ETiHKMmfr-k"
  },
  {
    "id": "jhoome-jo-pathaan",
    "title": "Jhoome Jo Pathaan",
    "artist": "Arijit Singh, Sukriti Kakar",
    "film": "Pathaan",
    "year": null,
    "duration": null,
    "videoId": "YxWlaYCA8MU"
  },
  {
    "id": "tu-aake-dekhle",
    "title": "Tu Aake Dekhle",
    "artist": "King",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "A66TYFdz8YA"
  },
  {
    "id": "dil-mere",
    "title": "Dil Mere",
    "artist": "The Local Train",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "jORm902Ubx4"
  },
  {
    "id": "rehna-tu",
    "title": "Rehna Tu",
    "artist": "A.R. Rahman",
    "film": "Delhi-6",
    "year": null,
    "duration": null,
    "videoId": "ZYGyuaEU2aA"
  },
  {
    "id": "masakali",
    "title": "Masakali",
    "artist": "Mohit Chauhan",
    "film": "Delhi-6",
    "year": null,
    "duration": null,
    "videoId": "HgGQeAy5VCA"
  },
  {
    "id": "maan-meri-jaan",
    "title": "Maan Meri Jaan",
    "artist": "King",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "VuG7ge_8I2Y"
  },
  {
    "id": "iktara",
    "title": "Iktara",
    "artist": "Kavita Seth, Amit Trivedi",
    "film": "Wake Up Sid",
    "year": null,
    "duration": null,
    "videoId": "akjdj6iHttY"
  },
  {
    "id": "dekho-na",
    "title": "Dekho Na",
    "artist": "Sonu Nigam, Sunidhi Chauhan",
    "film": "Fanaa",
    "year": null,
    "duration": null,
    "videoId": "v4h5iPlxj0c"
  },
  {
    "id": "namastute",
    "title": "Namastute",
    "artist": "Seedhe Maut",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "XbEEl8EKFSo"
  },
  {
    "id": "softly",
    "title": "Softly",
    "artist": "Karan Aujla, Ikky",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "-Chif1XK2e8"
  },
  {
    "id": "nazm-nazm",
    "title": "Nazm Nazm",
    "artist": "Arko",
    "film": "Bareilly Ki Barfi",
    "year": null,
    "duration": null,
    "videoId": "JihNlsapeQw"
  },
  {
    "id": "sajni",
    "title": "Sajni",
    "artist": "Arijit Singh, Ram Sampath",
    "film": "Laapataa Ladies",
    "year": null,
    "duration": null,
    "videoId": "k3g_WjLCsXM"
  },
  {
    "id": "tu-hai-kahan",
    "title": "Tu Hai Kahan",
    "artist": "AUR",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "OF87nVLU09Q"
  },
  {
    "id": "o-maahi",
    "title": "O Maahi",
    "artist": "Arijit Singh",
    "film": "Dunki",
    "year": null,
    "duration": null,
    "videoId": "pCYojfACnzQ"
  },
  {
    "id": "wishlist",
    "title": "Wishlist",
    "artist": "Dino James",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "hFGG7T3Mq3w"
  },
  {
    "id": "liggi",
    "title": "Liggi",
    "artist": "Ritviz",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "BXICjrqJ-SY"
  },
  {
    "id": "chupke-se",
    "title": "Chupke Se",
    "artist": "Sadhana Sargam",
    "film": "Saathiya",
    "year": null,
    "duration": null,
    "videoId": "pf31eHcgApY"
  },
  {
    "id": "gumaan",
    "title": "Gumaan",
    "artist": "Young Stunners",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "wujPjV1pigc"
  },
  {
    "id": "doobey",
    "title": "Doobey",
    "artist": "OAFF, Savera, Lothika",
    "film": "Gehraiyaan",
    "year": null,
    "duration": null,
    "videoId": "0zs3BZYgVTQ"
  },
  {
    "id": "millionaire",
    "title": "Millionaire",
    "artist": "Yo Yo Honey Singh",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "m1R98CwyDbw"
  },
  {
    "id": "kesariya",
    "title": "Kesariya",
    "artist": "Arijit Singh",
    "film": "BrahmÄstra",
    "year": null,
    "duration": null,
    "videoId": "W1S9AbHpWFY"
  },
  {
    "id": "choo-lo",
    "title": "Choo Lo",
    "artist": "The Local Train",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "sFMRqxCexDk"
  },
  {
    "id": "barso-re",
    "title": "Barso Re",
    "artist": "Shreya Ghoshal",
    "film": "Guru",
    "year": null,
    "duration": null,
    "videoId": "asw-wTDzGUQ"
  },
  {
    "id": "phir-se-ud-chala",
    "title": "Phir Se Ud Chala",
    "artist": "Mohit Chauhan",
    "film": "Rockstar",
    "year": null,
    "duration": null,
    "videoId": "-3gQ6HIkRys"
  },
  {
    "id": "rimjhim-gire-sawan",
    "title": "Rimjhim Gire Sawan",
    "artist": "Kishore Kumar",
    "film": "Manzil",
    "year": null,
    "duration": null,
    "videoId": "kAU8_00hAhs"
  },
  {
    "id": "pasoori",
    "title": "Pasoori",
    "artist": "Ali Sethi & Shae Gill",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "F9Oh65CwKFg"
  },
  {
    "id": "tum-se-hi",
    "title": "Tum Se Hi",
    "artist": "Mohit Chauhan",
    "film": "Jab We Met",
    "year": null,
    "duration": null,
    "videoId": "xo3ex0xDYVA"
  },
  {
    "id": "machayenge",
    "title": "Machayenge",
    "artist": "Emiway Bantai",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "zaCbuB3w0kg"
  },
  {
    "id": "ilahi",
    "title": "Ilahi",
    "artist": "Arijit Singh",
    "film": "Yeh Jawaani Hai Deewani",
    "year": null,
    "duration": null,
    "videoId": "06A8HBwdA2k"
  },
  {
    "id": "jaadugar",
    "title": "Jaadugar",
    "artist": "Paradox",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "IOcGS4D1tM0"
  },
  {
    "id": "faasle",
    "title": "Faasle",
    "artist": "Aditya A",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "EiiOYwqk3A0"
  },
  {
    "id": "qaafirana",
    "title": "Qaafirana",
    "artist": "Arijit Singh, Nikhita Gandhi",
    "film": "Kedarnath",
    "year": null,
    "duration": null,
    "videoId": "ZmcBC9-wAXM"
  },
  {
    "id": "heeriye",
    "title": "Heeriye",
    "artist": "Jasleen Royal ft. Arijit Singh",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "RLzC55ai0eo"
  },
  {
    "id": "hawaayein",
    "title": "Hawaayein",
    "artist": "Arijit Singh",
    "film": "Jab Harry Met Sejal",
    "year": null,
    "duration": null,
    "videoId": "lBACSadCKaQ"
  },
  {
    "id": "ghar",
    "title": "Ghar",
    "artist": "Mohit Chauhan, Nikhita Gandhi",
    "film": "Jab Harry Met Sejal",
    "year": null,
    "duration": null,
    "videoId": "Z_L9lD9H2dA"
  },
  {
    "id": "ishq",
    "title": "Ishq",
    "artist": "Faheem Abdullah & Rauhan Malik",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "gKD1AhmpOoU"
  },
  {
    "id": "bheegi-bheegi-raaton-mein",
    "title": "Bheegi Bheegi Raaton Mein",
    "artist": "Kishore Kumar, Lata Mangeshkar",
    "film": "Ajnabee",
    "year": null,
    "duration": null,
    "videoId": "-mKSeBJ_okY"
  },
  {
    "id": "aaj-din-chadheya",
    "title": "Aaj Din Chadheya",
    "artist": "Rahat Fateh Ali Khan",
    "film": "Love Aaj Kal",
    "year": null,
    "duration": null,
    "videoId": "TpowQfz8hdo"
  },
  {
    "id": "saibo",
    "title": "Saibo",
    "artist": "Shreya Ghoshal, Tochi Raina",
    "film": "Shor in the City",
    "year": null,
    "duration": null,
    "videoId": "kQkH6Ch8Kbg"
  },
  {
    "id": "tum-jab-paas",
    "title": "Tum Jab Paas",
    "artist": "Prateek Kuhad",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "WPi1xgc-iGo"
  },
  {
    "id": "pehle-bhi-main",
    "title": "Pehle Bhi Main",
    "artist": "Vishal Mishra",
    "film": "Animal",
    "year": null,
    "duration": null,
    "videoId": "9UmoVnBSm5k"
  },
  {
    "id": "khatta-flow",
    "title": "Khatta Flow",
    "artist": "Seedhe Maut ft. KR$NA",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "i0SP9dL-km8"
  },
  {
    "id": "sham",
    "title": "Sham",
    "artist": "Amit Trivedi",
    "film": "Aisha",
    "year": null,
    "duration": null,
    "videoId": "EhN3PXxcYR4"
  },
  {
    "id": "gul",
    "title": "Gul",
    "artist": "Anuv Jain",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "SmaY7RfBgas"
  },
  {
    "id": "kabira",
    "title": "Kabira",
    "artist": "Tochi Raina, Rekha Bhardwaj",
    "film": "Yeh Jawaani Hai Deewani",
    "year": null,
    "duration": null,
    "videoId": "7jZwAl0ArQw"
  },
  {
    "id": "samjho-na",
    "title": "Samjho Na",
    "artist": "Aditya Rikhari",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "wedxycztUAs"
  },
  {
    "id": "darasal",
    "title": "Darasal",
    "artist": "Atif Aslam",
    "film": "Raabta",
    "year": null,
    "duration": null,
    "videoId": "eCX2qFg2qhc"
  },
  {
    "id": "kun-faya-kun",
    "title": "Kun Faya Kun",
    "artist": "A.R. Rahman, Javed Ali, Mohit Chauhan",
    "film": "Rockstar",
    "year": null,
    "duration": null,
    "videoId": "T94PHkuydcw"
  },
  {
    "id": "tip-tip-barsa-pani",
    "title": "Tip Tip Barsa Pani",
    "artist": "Udit Narayan, Alka Yagnik",
    "film": "Mohra",
    "year": null,
    "duration": null,
    "videoId": "HyKuXycQXkg"
  },
  {
    "id": "sahiba",
    "title": "Sahiba",
    "artist": "Jasleen Royal, Stebin Ben",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "Npd94-t1Lv0"
  },
  {
    "id": "udaarian",
    "title": "Udaarian",
    "artist": "Satinder Sartaaj",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "k9rPE-vfRRU"
  },
  {
    "id": "kahani-suno-2-0",
    "title": "Kahani Suno 2.0",
    "artist": "Kaifi Khalil",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "DtA5ulL4ZkY"
  },
  {
    "id": "kasoor",
    "title": "Kasoor",
    "artist": "Prateek Kuhad",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "iOIF74Hk80A"
  },
  {
    "id": "cold-mess",
    "title": "Cold/Mess",
    "artist": "Prateek Kuhad",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "DE6YvcRrUoo"
  },
  {
    "id": "yeh-raaten-yeh-mausam",
    "title": "Yeh Raaten Yeh Mausam",
    "artist": "Kishore Kumar",
    "film": "Sanam",
    "year": null,
    "duration": null,
    "videoId": "zMGYCKr5trw"
  },
  {
    "id": "mere-gully-mein",
    "title": "Mere Gully Mein",
    "artist": "Divine, Naezy",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "NrVefnrjGMo"
  },
  {
    "id": "saiyaara",
    "title": "Saiyaara",
    "artist": "Tanishk Bagchi, Faheem Abdullah",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "HQp0DwtTP18"
  },
  {
    "id": "what-jhumka",
    "title": "What Jhumka?",
    "artist": "Arijit Singh, Jonita Gandhi",
    "film": "Rocky Aur Rani Kii Prem Kahaani",
    "year": null,
    "duration": null,
    "videoId": "vee_P6pIv_E"
  },
  {
    "id": "ghodey-pe-sawar",
    "title": "Ghodey Pe Sawar",
    "artist": "Sireesha Bhagavatula",
    "film": "Qala",
    "year": null,
    "duration": null,
    "videoId": "q05AbgNey6w"
  },
  {
    "id": "elevated",
    "title": "Elevated",
    "artist": "Shubh",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "I1nX5EuvwzE"
  },
  {
    "id": "kho-gaye-hum-kahan",
    "title": "Kho Gaye Hum Kahan",
    "artist": "Jasleen Royal, Prateek Kuhad",
    "film": "Baar Baar Dekho",
    "year": null,
    "duration": null,
    "videoId": "kY7a_ReAcas"
  },
  {
    "id": "baarishein",
    "title": "Baarishein",
    "artist": "Anuv Jain",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "NLKwRW2y-sg"
  },
  {
    "id": "humble-poet",
    "title": "Humble Poet",
    "artist": "Bella",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "OomxO1e6tRM"
  },
  {
    "id": "roobaroo",
    "title": "Roobaroo",
    "artist": "A.R. Rahman",
    "film": "Rang De Basanti",
    "year": null,
    "duration": null,
    "videoId": "8kMv5ssr6Dw"
  },
  {
    "id": "maina",
    "title": "Maina",
    "artist": "Seedhe Maut",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "uw17Mgm5i8k"
  },
  {
    "id": "subhanallah",
    "title": "Subhanallah",
    "artist": "Sreerama Chandra",
    "film": "Yeh Jawaani Hai Deewani",
    "year": null,
    "duration": null,
    "videoId": "PdjC8e7GFWg"
  },
  {
    "id": "baller",
    "title": "Baller",
    "artist": "Shubh",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "NSVUw0ydxBw"
  },
  {
    "id": "gehraiyaan-title-track",
    "title": "Gehraiyaan (Title Track)",
    "artist": "Lothika",
    "film": "Gehraiyaan",
    "year": null,
    "duration": null,
    "videoId": "zY0DoXNjgMA"
  },
  {
    "id": "obsessed",
    "title": "Obsessed",
    "artist": "Riar Saab, Abhijay Sharma",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "aCIZd2Z423w"
  },
  {
    "id": "downers-at-dusk",
    "title": "Downers At Dusk",
    "artist": "Talha Anjum, Umair",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "lXP_5tWMuFQ"
  },
  {
    "id": "pyaar-hota-kayi-baar-hai",
    "title": "Pyaar Hota Kayi Baar Hai",
    "artist": "Arijit Singh",
    "film": "Tu Jhoothi Main Makkaar",
    "year": null,
    "duration": null,
    "videoId": "MT0A5bajA6Q"
  },
  {
    "id": "abhi-na-jao-chhod-kar",
    "title": "Abhi Na Jao Chhod Kar",
    "artist": "Mohd. Rafi",
    "film": "Hum Dono",
    "year": null,
    "duration": null,
    "videoId": "mfEQgoVi7P4"
  },
  {
    "id": "tainu-khabar-nahi",
    "title": "Tainu Khabar Nahi",
    "artist": "Arijit Singh, Sachin-Jigar",
    "film": "Munjya",
    "year": null,
    "duration": null,
    "videoId": "9QpmsrYO4cc"
  },
  {
    "id": "chaleya",
    "title": "Chaleya",
    "artist": "Arijit Singh, Shilpa Rao",
    "film": "Jawan",
    "year": null,
    "duration": null,
    "videoId": "Bi7sSC046dk"
  },
  {
    "id": "52-bars",
    "title": "52 Bars",
    "artist": "Karan Aujla",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "PiqyZInLZmw"
  },
  {
    "id": "wishes",
    "title": "Wishes",
    "artist": "Hasan Raheem, Talwiinder, Umair",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "oE7lU2qj4rY"
  },
  {
    "id": "jo-tum-mere-ho",
    "title": "Jo Tum Mere Ho",
    "artist": "Anuv Jain",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "dSxvPy-5opc"
  },
  {
    "id": "pee-loon",
    "title": "Pee Loon",
    "artist": "Mohit Chauhan",
    "film": "Once Upon A Time In Mumbaai",
    "year": null,
    "duration": null,
    "videoId": "WCTro3qabjE"
  },
  {
    "id": "tere-vaaste",
    "title": "Tere Vaaste",
    "artist": "Varun Jain, Sachin-Jigar",
    "film": "Zara Hatke Zara Bachke",
    "year": null,
    "duration": null,
    "videoId": "SuSnEzOXVwo"
  },
  {
    "id": "chaand-baaliyan",
    "title": "Chaand Baaliyan",
    "artist": "Aditya A",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "Xi8Fabcb_MA"
  },
  {
    "id": "ek-ladki-ko-dekha-toh-aisa-laga",
    "title": "Ek Ladki Ko Dekha Toh Aisa Laga",
    "artist": "Kumar Sanu",
    "film": "1942: A Love Story",
    "year": null,
    "duration": null,
    "videoId": "H5sheEWfsOQ"
  },
  {
    "id": "aathma-rama",
    "title": "Aathma Rama",
    "artist": "Brodha V",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "SdxSQlk4Bws"
  },
  {
    "id": "waqt-ki-baatein",
    "title": "Waqt Ki Baatein",
    "artist": "Dream Note",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "D_qjmHvD8m8"
  },
  {
    "id": "nadaaniyan",
    "title": "Nadaaniyan",
    "artist": "Akshath",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "235bRee9PO4"
  },
  {
    "id": "soulmate",
    "title": "Soulmate",
    "artist": "Badshah ft. Arijit Singh",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "9aOgTYO5UKs"
  },
  {
    "id": "apna-bana-le",
    "title": "Apna Bana Le",
    "artist": "Arijit Singh, Sachin-Jigar",
    "film": "Bhediya",
    "year": null,
    "duration": null,
    "videoId": "u2NAuswnTKs"
  },
  {
    "id": "tere-hawale",
    "title": "Tere Hawale",
    "artist": "Arijit Singh, Shilpa Rao",
    "film": "Laal Singh Chaddha",
    "year": null,
    "duration": null,
    "videoId": "FiENDQapd4g"
  },
  {
    "id": "company",
    "title": "Company",
    "artist": "MC Stan",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "5vYQZYaO_5o"
  },
  {
    "id": "alag-aasmaan",
    "title": "Alag Aasmaan",
    "artist": "Anuv Jain",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "BmwiS-THm34"
  },
  {
    "id": "akhiyaan",
    "title": "Akhiyaan",
    "artist": "Mitraz",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "MHhsBGidWds"
  },
  {
    "id": "3-59-am",
    "title": "3:59 AM",
    "artist": "Divine",
    "film": "",
    "year": null,
    "duration": null,
    "videoId": "Itd89dfnxvU"
  }
]
} as const;
