// @ts-nocheck
import fs from "node:fs/promises";
import path from "node:path";

const dataDir = path.join(process.cwd(), "data");
async function readJson(filePath) { return JSON.parse((await fs.readFile(filePath, "utf8")).replace(/^\uFEFF/, "")); }

async function main() {
  const songs = await readJson(path.join(dataDir, "songs-to-import.json"));
  const approvals = await readJson(path.join(dataDir, "youtube-approved.json"));
  const additions = await readJson(path.join(dataDir, "playlist-additions.json")).catch(() => []);
  const approvalById = new Map(approvals.map((entry) => [entry.id, entry]));
  const tracks = songs.filter((song) => {
    const approval = approvalById.get(song.id);
    return approval?.approved === true && typeof approval.videoId === "string" && /^[A-Za-z0-9_-]{11}$/.test(approval.videoId);
  }).map((song) => {
    const approval = approvalById.get(song.id);
    return { id: song.id, title: song.title, artist: song.artist, film: song.film, year: null, duration: null, videoId: approval.videoId };
  });
  const existingIds = new Set(tracks.map((track) => track.id));
  const existingVideoIds = new Set(tracks.map((track) => track.videoId));
  for (const addition of additions) {
    if (addition.playlist !== "Late Night Drive" || existingIds.has(addition.id) || existingVideoIds.has(addition.videoId)) continue;
    tracks.push({ id: addition.id, title: addition.title, artist: addition.artist, film: addition.film, year: addition.year ?? null, duration: addition.duration ?? null, videoId: addition.videoId });
    existingIds.add(addition.id);
    existingVideoIds.add(addition.videoId);
  }
  const output = `// Generated by npm run playlist:build. Complete year/duration manually before use.\nexport const PLAYLISTS = {\n  "Late Night Drive": ${JSON.stringify(tracks, null, 2)}\n} as const;\n`;
  await fs.writeFile(path.join(dataDir, "tracks.ts"), output, "utf8");
  console.log(`Generated ${tracks.length} approved tracks in data/tracks.ts.`);
}

main().catch((error) => { console.error(`Playlist build stopped: ${error.message}`); process.exitCode = 1; });

